---
language: ruby
rvm:
- 1.9.2
- 1.9.3
- 2.0.0
env:
  global:
  - TRAVIS_SECURE_ENV_VARS: true
  - secure: ! 'Q1wjuxr364WRXFTDD8jdunJG59Xl2iYFtehm+5d6UAR9mY9Ohv4TLqT6QhHu

      1mdR575m90w3y1ZuS3NnzoUiMcrL+Osoza/tzBOch0+doXMqCXyZcgnSlNgV

      16TcY+GFYbBnGnlq+5UoBCjOb3eqHdWqoASdT4DPIijGmvEzBDs='
